export enum IconEnum {
  ALARM = `https://i.ibb.co/S7BxtDh/icons8-alarm-512.png`,
  ARTIFICIAL_INTELLIGENCE = `https://i.ibb.co/ph17BqP/icons8-artificial-intelligence-512.png`,
  BUG = `https://i.ibb.co/r7PHJS1/icons8-bug-512.png`,
  CANCEL = `https://i.ibb.co/cLM30Xb/icons8-cancel-512.png`,
  COOKIES = `https://i.ibb.co/RTp4YPx/icons8-cookies-512.png`,
  DEADBUG = `https://i.ibb.co/CmxGZG1/icons8-deadbug-512.png`,
  ERROR = `https://i.ibb.co/5jZmzSB/icons8-error-512.png`,
  FUTURAMA_PROFESSOR_FARNSWORTH = `https://i.ibb.co/4SsVxDQ/icons8-futurama-professor-farnsworth-512.png`,
  GIRL = `https://i.ibb.co/XSB6Vng/icons8-girl-1024.png`,
  INFORMATION = `https://i.ibb.co/vLSnVk6/icons8-information-512.png`,
  MOTIVATION_DAILY_QUOTES = `https://i.ibb.co/qJDxmc8/icons8-motivation-daily-quotes-512.png`,
  NEW = `https://i.ibb.co/YjzVm0c/icons8-new-512.png`,
  NEW_PRODUCT = `https://i.ibb.co/9p3Q17S/icons8-new-product-512.png`,
  RESTAURANT = `https://i.ibb.co/vXwNzWD/icons8-restaurant-512.png`,
  THE_FLASH_SIGN = `https://i.ibb.co/JkmQvS1/icons8-the-flash-sign-512.png`,
  WARNING_SHIELD = `https://i.ibb.co/41ccwXn/icons8-warning-shield-512.png`,
}
