/**
 * @description
 * Most of them comes from https://web.sonoma.edu/users/s/swijtink/teaching/philosophy_101/paper1/listemotions.htm
 */
export enum DiscordSoniaEmotionalStateEnum {
  AGITATED = `agitated`,
  ANGRY = `angry`,
  ANNOYED = `annoyed`,
  ANXIOUS = `anxious`,
  BORED = `bored`,
  COMFORTABLE = `comfortable`,
  CONCERNED = `concerned`,
  CRAZY = `crazy`,
  CYNIC = `cynic`,
  DARK = `dark`,
  DELIRIOUS = `delirious`,
  DEPRESSED = `depressed`,
  DEVASTATED = `devastated`,
  ENIGMATIC = `enigmatic`,
  ENLIGHTENED = `enlightened`,
  EUPHORIC = `euphoric`,
  EXCITED = `excited`,
  EXHAUSTED = `exhausted`,
  GOOFY = `goofy`,
  HOSTILE = `hostile`,
  MELANCHOLIC = `melancholic`,
  MISERABLE = `miserable`,
  NERVOUS = `nervous`,
  RATIONAL = `rational`,
  REBELLIOUS = `rebellious`,
  SENSITIVE = `sensitive`,
  SEXY = `sexy`,
  SUBMISSIVE = `submissive`,
  SURPRISED = `surprised`,
  TORMENTED = `tormented`,
  TROUBLED = `troubled`,
  UNHAPPY = `unhappy`,
  UPSET = `upset`,
  VENGEFUL = `vengeful`,
}
